baseURL = "http://example.org/"
languageCode = "en-us"

theme = "spf13/hyde"
summaryLength = 25

uglyURLs = true
canonifyURLs = true

googleAnalytics = "UA-158969760-1"

[taxonomies]
  serie = "series"
  tag = "tags"

[permalinks]
  posts = "/:year/:month/:day/:title"
