name: Hugo site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: srt32/hugo-action@v0.0.3
      with:
        args: --baseURL 'https://plippe.github.io/blog/' --destination docs
